// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("2.2")]
[assembly: AssemblyFileVersionAttribute("2.2")]
[assembly: AssemblyDescriptionAttribute("see: https://github.com/mrpinkzh/exas")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "2.2";
        internal const System.String AssemblyFileVersion = "2.2";
        internal const System.String AssemblyDescription = "see: https://github.com/mrpinkzh/exas";
    }
}
