// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.4.0")]
[assembly: AssemblyFileVersionAttribute("0.4.0")]
[assembly: AssemblyDescriptionAttribute("see: https://github.com/mrpinkzh/exas")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.0";
    }
}
